use_frameworks!

platform :ios, '11.0'

target 'ZZBase_Example' do
  pod 'ZZBase', :path => '../ZZBase.podspec'

  target 'ZZBase_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
